/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManagerLogGUI;

import LoginGUI.LoginGI;
import UserData.Login;
import UserData.LoginDB;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DSYS
 */
public class ManageCashiers extends javax.swing.JFrame {

    Login login;
    LoginDB logindb;
    ArrayList<Login> loginList;
    private DefaultTableModel TableModel;

    public ManageCashiers() {
        initComponents();
        TableModel = new DefaultTableModel();
        loginList = new ArrayList<Login>();
        logindb = new LoginDB();
        TableModel.addColumn("User ID");
        TableModel.addColumn("UserName");
        TableModel.addColumn("Password");
        Table.setModel(TableModel);
    }
 // Method to check if the user ID or username is already in use
    public boolean checkUserID() {
        try {
            BufferedReader br = new BufferedReader(new FileReader("UserDetails.txt"));
            String line;
            // Read the file line by line to check for duplicate user IDs or usernames
            try {
                while ((line = br.readLine()) != null) {
                    String extractID = line.split(":")[0];
                    String extractUsername = line.split(":")[1];
                    // Check if the entered user ID matches an existing ID
                    if (extractID.equals(txtuserID.getText())) {
                        JOptionPane.showMessageDialog(null, "This user ID already stored");
                        return false;
                    }
                    // Check if the entered username matches an existing username
                    if (extractUsername.equals(txtUsername.getText())) {
                        JOptionPane.showMessageDialog(null, "This username already stored");
                        return false;
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(ManageCashiers.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManageCashiers.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
// Method to verify if any required text fields are empty
    public boolean checkBlank() {
        if (txtuserID.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "User ID can't be zero");
            return false;
        }
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "UserName can't be blank");
            return false;
        }
        if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Password can't be blank");
            return false;
        }
        return true;
    }
// Method to check if the username and password meet system requirements
    public boolean checkconditions() {
        // Check if the username has at least 4 characters
        if (txtUsername.getText().length() < 4) {
            JOptionPane.showMessageDialog(null, "Your username should have 4 character");
            return false;
        }
        // Validate password requirements: at least 6 characters, includes '@' or '#', and contains at least one digit
        if (txtPassword.getText().length() < 6 || !(txtPassword.toString().contains("@") || txtPassword.toString().contains("#")) || !txtPassword.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "password should have @ or # with 6 characters including at lest one digit");
            return false;
        }
        return true;
    }
// Method to display all cashier login details from the database in a table format
    public void viewLoginDetails() {
        loginList = logindb.getAll();
        TableModel.setRowCount(0);
        for (Login logindetails : loginList) {
            int UserID = Integer.valueOf(logindetails.getUserID());
            String Username = logindetails.getUsername();
            String Password = logindetails.getPassword();
            TableModel.addRow(new Object[]{UserID, Username, Password});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btninsert = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        txtuserID = new javax.swing.JTextField();
        btnlogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        btninsert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btninsert.setText("Insert");
        btninsert.setFocusable(false);
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        jPanel1.add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setFocusable(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setFocusable(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btnview.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnview.setText("View all");
        btnview.setFocusable(false);
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setFocusable(false);
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 400, 360));
        jPanel1.add(txtuserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, -1));

        btnlogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setFocusable(false);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 360));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manager.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(700, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// Method triggered by the "Insert" button to add a new cashier to the system
    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        if (checkBlank() && checkUserID() && checkconditions()) {
            int UserID = Integer.valueOf(txtuserID.getText());
            String UserName = txtUsername.getText();
            String password = txtPassword.getText();
            loginList.add(login);
            login = new Login(UserID, UserName, password);
            if (logindb.add(login)) {
                JOptionPane.showMessageDialog(null, "Added Succesfully !");
                viewLoginDetails();
            } else {
                JOptionPane.showMessageDialog(null, "Can't acces to database");
            }
        }
    }//GEN-LAST:event_btninsertActionPerformed

//following method use to logout from the Manage cashier GUI to LoginGUI
    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        LoginGI logGI = new LoginGI();
        this.dispose();
        logGI.setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        viewLoginDetails();
    }//GEN-LAST:event_btnviewActionPerformed
// Method triggered by the "Delete" button to remove a cashier account from the system
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String userID = JOptionPane.showInputDialog(null, "Enter User ID");
        if (userID == null || userID.trim().isEmpty()) {
            return;  // Exit the method to close the dialog
        }
        int UserID = Integer.parseInt(userID);
        if (logindb.delete(UserID)) {
            JOptionPane.showMessageDialog(null, "Deleted successfully");
            viewLoginDetails();  // Refresh or view details
        } else {
            JOptionPane.showMessageDialog(null, "User ID not found");
        }
    }//GEN-LAST:event_btndeleteActionPerformed
// Method triggered by the "Update" button to modify an existing cashier account in the system
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        if (checkBlank()) {
            int UserID = Integer.valueOf(txtuserID.getText());
            String UserName = txtUsername.getText();
            String Password = txtPassword.getText();
            login = new Login(UserID, UserName, Password);
            if (logindb.update(login)) {
                JOptionPane.showMessageDialog(null, "Updated Succesfully");
                viewLoginDetails();
            } else {
                JOptionPane.showMessageDialog(null, "Updated Unsuccesfully");
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

// Method triggered by the "Search" button to find cashier accounts in the system by User ID
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        if (txtuserID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "User ID can't be empty");
        } else {
            int UserID = Integer.valueOf(txtuserID.getText());
            loginList = logindb.Search(UserID);
            TableModel.setRowCount(0);
            for (Login logDetails : loginList) {
                int ID = logDetails.getUserID();
                String Username = logDetails.getUsername();
                String Password = logDetails.getPassword();
                TableModel.addRow(new Object[]{ID, Username, Password});
            }
        }
    }//GEN-LAST:event_btnsearchActionPerformed
// Method triggered when a row in the table is clicked to display details on textfields
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        // get the model from the jtable
        txtuserID.disable();
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        // get the selected row index
        int selectedRowIndex = Table.getSelectedRow();
        txtuserID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtUsername.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtPassword.setText(model.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtuserID.setEnabled(true);
        txtuserID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCashiers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnview;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtuserID;
    // End of variables declaration//GEN-END:variables
}
